name: CD Cleanup on Branch Deletion

on:
  delete:
    branches-ignore: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.ORG_ACCESS_TOKEN }}
        repository: 'SYDE-25/Class-Profile-CD'
        path: main

    - name: Delete Branch from CD Repo
      shell: bash
      run: |
        rm -rf ./${GITHUB_REF#refs/heads/}

    - name: Purge Empty Folders
      shell: bash
      run: |
        find . -type d -depth -empty -exec rmdir "{}" \;

    - name: Push Changes to CD Repo
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.CD_DEPLOY_KEY }}
        external_repository: SYDE-25/Class-Profile-CD
        publish_branch: main
        publish_dir: ./
        destination_dir: ./