name: Prod Deploy to Github Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Yarn Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Yarn Export
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: export
        
    - name: Repair File Paths
      run: | 
        sudo find ./out -type f -name "*.html" -exec sed -i 's/\/_next/.\/_next/g' {} +

    - name: Deploying to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out